### ISSUE TITLE
Extra whitespace in CC

### ISSUE THREAD

**Issue by HowieHye** [leminlimez/CowabungaLite#21]
There is something wrong when I enable "Control Center".
![IMG_6DAD48A660C8-1](https://github.com/leminlimez/CowabungaLite/assets/36627364/6ce377cb-ff71-402a-b6ba-eaa7a634a480)
<img width="1038" alt="image" src="https://github.com/leminlimez/CowabungaLite/assets/36627364/9ba8417d-2ee1-4248-b420-6e1a09e90918">

**Comment by project11x** [comment]
i can't even disable it

**Comment by HowieHye** [comment]
> i can't even disable it

Remove items without icons in Setting may work. Such as "MediaControlsAudioModule" etc. Just waitting for fixing.

**Comment by leminlimez** [comment]
cant be fixed

**Comment by dezbracaty** [comment]
> 

How to fix this bug ? Only waiting for new release ?

**Comment by Ssiswent** [comment]
> > i can't even disable it
> 
> Remove items without icons in Setting may work. Such as "MediaControlsAudioModule" etc. Just waitting for fixing.

The same problem, if do like this, CC presets will revert to original.

**Comment by leminlimez** [comment]
there is a revert option in v1.1.1

**Comment by Ssiswent** [comment]
> there is a revert option in v1.1.1

Sry, I mean if I `Remove items without icons in Setting may work. Such as "MediaControlsAudioModule" etc`,
my CC will be changed to default.
