### ISSUE TITLE
Doesnt detect device

### ISSUE THREAD

**Issue by jasonly28** [leminlimez/CowabungaLite#22]
it doesn’t detect my device i dont know what to do im using a virtual box

**Comment by z0mbieslayer** [comment]
If my experience is anything to go by, it's that virtualbox doesn't usually work well with these types on programs specifically on ios devices (that is if this is the same issue that checkra1n has on VMs). I seem to remember the only way of circumventing this was by running qemu on a linux distro and forwarding the whole usb controller to the kvm running macos. Other than that, you're probably gonna have to either hackintosh or run it on bare metal.
