### ISSUE TITLE
Can't Skip Setup

### ISSUE THREAD

**Issue by Ssiswent** [leminlimez/CowabungaLite#28]
I enabled this option, but every time I apply tweaks and reboot, it will make me do some settings.
<img width="936" alt="image" src="https://github.com/leminlimez/CowabungaLite/assets/37449310/f2e3d0e0-4a83-4886-ab04-34b80f80e36c">

**Comment by leminlimez** [comment]
this issue cannot be avoided, also an ios  17 bug
