### ISSUE TITLE
Bug with iOS17 carrier text

### ISSUE THREAD

**Issue by Shad0w23333** [leminlimez/CowabungaLite#32]
Cowabunga Lite cannot change carrier text on iOS17 or the default

**Comment by leminlimez** [comment]
yes it can, make sure yours is restoring correctly

**Comment by Shad0w23333** [comment]
sorry, but how to restore it properly? any hits?

**Comment by leminlimez** [comment]
enable the tweak and changing the carrier text then restore

**Comment by Shad0w23333** [comment]
I tried multiple times on iOS17 beta2, and I'm pretty sure it's not working properly...

**Comment by Shad0w23333** [comment]
> try again in v1.2

Sadly, after 10 times of attempts, it is confirmed not working on any iOS17 beta version.
