### ISSUE TITLE
No work in hackintosh anymore. 1.2, 1.1.1 works good.

### ISSUE THREAD

**Issue by LifelessLife** [leminlimez/CowabungaLite#35]
https://images4.imagebam.com/95/bf/1e/MEMFACV_o.png

**Comment by gorouflex** [comment]
me too,won't work

**Comment by LifelessLife** [comment]
Windows version didn't change animation speed at all.
Im back to 1.1.1 on macOS and all is good.

**Comment by LifelessLife** [comment]
Any possibilities to add option to change image of the DEFAULT wallet card? I've update today from 16.2.1 to 17b2 and I miss this option, which was in normal Cowabunga.

**Comment by leminlimez** [comment]
not possible afaik

**Comment by leminlimez** [comment]
also, the hackintosh v1.2 issue will be fixed in v1.2.1

**Comment by leminlimez** [comment]
fixed
