### ISSUE TITLE
Error loading apps. Please try again.

### ISSUE THREAD

**Issue by Ssiswent** [leminlimez/CowabungaLite#36]
<img width="936" alt="image" src="https://github.com/leminlimez/CowabungaLite/assets/37449310/6f96f913-c70b-4775-b78e-a96330670e88">

MacOS 14 beta2
iOS 17 beta2

This is good in CowabungaLite 1.1 version.

**Comment by leminlimez** [comment]
fixed, sorry about that

**Comment by Ssiswent** [comment]
> fixed, sorry about that

Thanks a lot!
