### ISSUE TITLE
Version 1.2 not detecting connected devices

### ISSUE THREAD

**Issue by NekoMichi** [leminlimez/CowabungaLite#37]
Tested on iMac18,2 running macOS Ventura 13.4.1

When version 1.2 is launched, the main page always displays "No Device, Please connect a device." The list at the top-left always displays "None" even after clicking on the refresh button. The connected devices show up in Finder and are also correctly detected in version 1.1.1.

Upon first launch, version 1.1.1 requests permission to access Documents whereas version 1.2 does not, could this be why?

**Comment by leminlimez** [comment]
known issue, it is not the documents folder, i am releasing a fix soon

**Comment by leminlimez** [comment]
fixed
