### ISSUE TITLE
App Store debug gesture?

### ISSUE THREAD

**Issue by Spykington** [leminlimez/CowabungaLite#38]
Hey- love your work. 
I haven't been able to figure out what the "App Store debug gesture" feature is referring to? I've googled and read through the repo pretty thoroughly but haven't found anything about it. 
The reason I'm asking is because I'm having an issue on my ios 15.2.1 iPhone 11 Pro Max where I'm no longer able to install or update apps, or even install using a macOS installer or via a windows computer (so like using a sideloader). This only started happening shortly after using trollstore, so I deleted it but the issue still remains. The creator of trollstore has denied that his app is the cause (yet is the only thing that was on my phone that could have caused it? Makes no sense.), And from as far as I can tell from the syslogs when trying an install, it looks like it's a permissions issue to do with possibly lsd, containermanagerd or installd and I really don't want to have to do a full "erase all content and settings" and reset of my phone. It'll take too damn long, and that's why I was wondering if this feature you've got in your app "App Store debug gesture" would actually check/repair/debug system default permissions for AppStore related processes, or at least give me a bit more information so I can try correct the issue myself. 
But if that's completely unrelated to this feature, I completely get it and my apologies for assuming it might help! Haha 
But if you had any thoughts or ideas on how I could fix this without wiping my phone, I'd love to hear your suggestions too! Cos that trollstore/Opa33 or whatever hasn't even attempted to address or correct the issue at all when it's been raised by other users and judging by the ticket history on that repo, if I ask him to help he's just gonna deny that his app caused it and close the ticket, and just be a dick about it. 

Thanks for your time and looking forward to your reply.

**Comment by leminlimez** [comment]
not exactly sure how to get to it but it is related to doing a gesture inside of the app store app itself

as for the apps issue, it seems like partial restores sometimes screws up sideloaded apps and idk why
