### ISSUE TITLE
Is it supposed to set all animation speed?

### ISSUE THREAD

**Issue by smit-io** [leminlimez/CowabungaLite#42]
I have tried the Windows version and it only speeds up one type of animation for me - the app opening animation.
The folder opening animation is still at the same speed.

**Comment by augustobob** [comment]
Maybe it only speed up uikit animations like some ios tweaks did, Apollo app behaved strange after changing animation speed for me.

**Comment by leminlimez** [comment]
> Maybe it only speed up uikit animations like some ios tweaks did, Apollo app behaved strange after changing animation speed for me.

yes, it only modifies uikit animations
