### ISSUE TITLE
Dude, you fucking deleted all my photos.

### ISSUE THREAD

**Issue by SevereDev** [leminlimez/CowabungaLite#50]
Dude, you fucking deleted all my photos. I didn't know it was going to reset my whole fucking iPad!

**Comment by LunarN0v4** [comment]
Did you select "Do not transfer apps and data" when it restored the device?
The restore should've only changed a few files, so this is on you, not the developer of this.
Also, read the README.md when you're installing something from GitHub.

**Comment by LunarN0v4** [comment]
If you feel like actually helping out, give us the logs and what you did to get here.
Things such as what you pressed after the restore, logs from the Cowabunga Lite GUI, etc.

**Comment by leminlimez** [comment]
did you read the Readme? it says to back up your device in cases like this

seems like you did not properly set up the device and chose to transfer data

**Comment by LunarN0v4** [comment]
> did you read the Readme? it says to back up your device in cases like this
> 
> seems like you did not properly set up the device and chose to transfer data

this ^^

**Comment by SevereDev** [comment]
yeah I did. I installed everything and I created a backup. At least it said
it was creating a backup.

**Comment by LunarN0v4** [comment]
> yeah I did. I installed everything and I created a backup. At least it said it was creating a backup.
It creates a backup which it then restores to your device, it's a partial restore so no other data should've been touched.
The backup it makes is not a real backup, if you want a real backup that you can actually restore, use iTunes or something.
Did you choose to transfer data? If you did, that is why this happened.
Please practice backup etiquette when using software intended to modify the device, this is a common mistake and we learn from mistakes, make a backup before using the software.

**Comment by leminlimez** [comment]
it is a real backup, there is no such thing as a fake backup

**Comment by LunarN0v4** [comment]
> it is a real backup, there is no such thing as a fake backup

I didn't exactly mean it in that way, I needa check how this thing works again because I thought it constructed its own backup and then sent that to the device (like partial restores with iBackupBot)
