### ISSUE TITLE
Does Cowabunga Lite affect updates?

### ISSUE THREAD

**Issue by Skyyblaze** [leminlimez/CowabungaLite#51]
My iPhone 13 Mini is currently running on iOS 16.1 and since I've learned to live without a Jailbreak I want to DelayOTA to 16.5 and instead do a bit theming with Cowabunga Lite. However I wonder, would theming with it affect me eventually upgrading to iOS 17 in the future?

All I've did on 16.1 with the normal Cowabunga so far is mess with sounds a bit and changing the graphics of my Apple Wallet cards (which somehow persisted even after reboots) but I hope this won't affect updates at all.

**Comment by leminlimez** [comment]
no, the only thing in cowabunga lite that could possibly effect you is the status bar, but ios 16.3+ is compatible with ios 17 so you should be fine
