### ISSUE TITLE
Icon theming only gets 10 apps

### ISSUE THREAD

**Issue by itaysharir** [leminlimez/CowabungaLite#73]
When I apply a theme only about 10 apps are themed.
I'm on 17.0.3, 13 Pro, M1 MBP.

When I go to "App Settings" this is what I see:
![Screenshot 2023-11-03 at 15 40 55](https://github.com/leminlimez/CowabungaLite/assets/87126382/a2926c83-da35-4fc0-ae87-106019bd8920)
Which is not even close to all apps.

Is there a solution? Thanks in advance.

**Comment by leminlimez** [comment]
it only shows the apps on the home screen (including hidden pages)

app library apps are not included
