### ISSUE TITLE
Can it change the system's region of the device in the future?

### ISSUE THREAD

**Issue by Anertz** [leminlimez/CowabungaLite#8]
To be specific, can it edit this file?
`/var/containers/Shared/SystemGroup/systemgroup.com.apple.mobilegestaltcache/Library/Caches/com.apple.MobileGestalt.plist`

**Comment by leminlimez** [comment]
no, it cannot edit caches

**Comment by Anertz** [comment]
For this purpose I would like to disable the sound of the camera, is this possible in some other way?

**Comment by leminlimez** [comment]
not possible
